## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy an event-triggered serverless application"
stackDescription: "Deploy an event-triggered serverless application"
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - ocir_repo_name

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - ocir_user_name
  - ocir_user_password
  - show_advanced 

- title: OSS Bucket Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - bucket

- title: Networking Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - VCN-CIDR
  - fnsubnet-CIDR
    
variables:
  
  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: "Compartment"
    description: "Choose compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"
    description: "Choose region where you want to deploy the resources defined by this stack."

  ocir_user_name:
    type: string
    required: true
    visibile: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)" 

  ocir_user_password:
    type: password
    required: true
    visibile: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 

  # Optional Configuration
  VCN-CIDR:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN's CIDR block where Fn App will be deployed."

  fnsubnet-CIDR:
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet CIDR"
    description: "Choose Public Subnet's CIDR where Fn App will be deployed."  

  bucket:
    type: string
    required: false
    default: "bucket"
    title: "Bucket Name"
    description: "Choose bucket name"

outputs:

  buckets_created:
    title: "Created buckets"
    displayText: "Created buckets"
    type: copyableString
    visible: true
